# 工作流名称
name: Sync-DockerHub-Images-to-Tencent-TCR

# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to Tencent-TCR.


# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncImages:
    runs-on: ubuntu-latest
    environment: 
      name: main
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ccr.ccs.tencentyun.com
        username: 100023037345
        password: Eric#2021
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy docker://docker.io/mpromonet/webrtc-streamer:latest docker://ccr.ccs.tencentyun.com/jiangore/mpromonet/webrtc-streamer:latest